---
name: Bug report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.

  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description:
        A clear and concise description of what you expected to happen.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: desktop
    attributes:
      label: Desktop (please complete the following information)
      value: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    id: mobile
    attributes:
      label: Mobile (please complete the following information)
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
